global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'email@gmail.com'
  smtp_auth_username: 'email@gmail.com'
  smtp_auth_password: 'email-password'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'receiver-email@example.com'
        send_resolved: true


